### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#1]
[debug.log](https://github.com/tmarenko/mff_auto/files/5177661/debug.log)
Tried Mulitple time But still same can't even set Daily Trivia to work Any Suggestions.

Setting :
for nox 
![Screenshot (4)](https://user-images.githubusercontent.com/7036189/92299770-1a50c580-ef73-11ea-9bb1-22c30da1b460.png)

**Comment by tmarenko** [comment]
In log file all that I can is that bot can't get to Content Status board. Not sure why though.
Can you ask some question to help found out the bug?
1) What's your PC monitor resolution?
2) Is there a reason to use NoxPlayer 6.6.1.2 instead of suggested 6.3.0.5 version? You'll lose ability to restart game for sure.
3) Does `Game screen` in bot's window show actual game screen of NoxPlayer (full game image)?
4) Does something happens in the game when you're starting the bot? Does it click buttons, navigate through menus or it just does nothing at all?

**Comment by tmarenko** [comment]
I found an issue when NoxWindow received wrong coordinates if you had display scale over 100% in Windows.
Please try new release with fix: https://github.com/tmarenko/mff_auto/releases/tag/0.4.4

**Comment by dbzdivik** [comment]
> In log file all that I can see is that bot can't get to Content Status board. Not sure why though.
> Can you answer some question to help found out the bug?
> 
> 1. What's your PC monitor resolution?
> 2. Is there a reason to use NoxPlayer 6.6.1.2 instead of suggested 6.3.0.5 version? You'll lose ability to restart game for sure.
> 3. Does `Game screen` in bot's window show actual game screen of NoxPlayer (full game image)?
> 4. Does something happens in the game when you're starting the bot? Does it click buttons, navigate through menus or it just does nothing at all?

1. 1920X1080
2. Its working fine means i'm able to restart game.
3. It doesn't do anything
4. same goes as of 3.

After 0.4.4 it made some progress

Trivia Working, Also some Levels but i think Farm Bios isn't working fine as Look to logs also on CMD there is msg loop for Dispaly width .
[debug.log](https://github.com/tmarenko/mff_auto/files/5183701/debug.log)
![Screenshot (5)](https://user-images.githubusercontent.com/7036189/92400457-9a308880-f149-11ea-8827-5046485e40ac.png)


Also it would be great, If i add dooms day then drop down menu doesn't show it again to avoid conflict

**Comment by tmarenko** [comment]
1. Are you using scaling in your OS? I'm assuming you're running Windows (because there is no support for Mac/Linux). Try to switch `Display  settings -> Scale and layout` to 100%. I think I fixed this problem in https://github.com/tmarenko/mff_auto/commit/fc794ccdad2a502a5fa8479f8de7a5a706940224 but you can try it just to make sure.
2. I tried NoxPlayer 6.6.1.2 and it definitely doesn't have keyboard shortcut to force close the game (CTRL+7). So you can't farm bios because the logic of farming is to force close game if shifter didn't appear in the mission. More about here: https://www.reddit.com/r/future_fight/comments/963tcg/ps_farming_the_max_amount_of_colossus_bios/
If you want just to usually run the mission then don't check "Farm bios" checkbox.
3 and 4. Did 0.4.4 fixed it?

Message loops and Nox initialization fixed in the last release: https://github.com/tmarenko/mff_auto/releases/tag/0.4.5

About adding duplicate game modes: sometimes you want to do that. For example, you're running Heroic Quest and you want to do World Bosses 3 times and after some another missions you want to do World Bosses again for 2 times. 
Usually bot checks stage counter or ability to get to the mission so same multiple modes shouldn't be an issue.

**Comment by dbzdivik** [comment]
Ok Thank will try. Also My scaling is 125%.

Also some more issues :
Timeline Battle : if Loading circle isn't there, then Bot Click on Change Opponent Option 2-3 times uncessarily, Also sometimes stuck of after game is finished
Dimesion Mission : Didn't undestand Stage selection also there should be limit for dificulity level also.

Error Logs: 
2020-09-07 20:57:08,159 - dimension_missions - INFO - Dimension Missions: decreasing stage difficulty level.
2020-09-07 20:57:08,722 - dimension_missions - DEBUG - Dimensions Missions: current stage level is 713
2020-09-07 20:57:09,247 - dimension_missions - INFO - Dimension Missions: decreasing stage difficulty level.
2020-09-07 20:57:09,790 - dimension_missions - DEBUG - Dimensions Missions: current stage level is 712
2020-09-07 20:57:10,290 - dimension_missions - INFO - Dimension Missions: decreasing stage difficulty level.
2020-09-07 20:57:10,970 - dimension_missions - DEBUG - Dimensions Missions: current stage level is 711
2020-09-07 20:57:11,666 - dimension_missions - INFO - Dimension Missions: decreasing stage difficulty level.

**Comment by tmarenko** [comment]
Timeline Battle: changing opponent is here for minimize point loss (common strategy in Vibranuim League). I'll add a checkbox option for that later.
I'll loot into stucking problem. Probably need to add waiting for button animation.

Dimension Mission: looks like Tesseract can't recognize number properly. I changed threshold value of level counter in 0.4.5 (https://github.com/tmarenko/mff_auto/commit/cdc3484b6267a098987a86484ceb7c28ed994749) so tell me please in which version you encountered this problem.

**Comment by dbzdivik** [comment]
> Dimension Mission: looks like Tesseract can't recognize number properly. I changed threshold value of level counter in 0.4.5 ([cdc3484](https://github.com/tmarenko/mff_auto/commit/cdc3484b6267a098987a86484ceb7c28ed994749)) so tell me please in which version you encountered this problem.

Currently, I'm testing 0.4.4 haven't downloaded 0.4.5 wanted to notify with all errors.

**Comment by tmarenko** [comment]
Ok, tell me then if you encounter this problem again.
I'll close this issue because the main bug (DPI scaling) was fixed in https://github.com/tmarenko/mff_auto/releases/tag/0.4.4
