### ISSUE TITLE
Coop play issue

### ISSUE THREAD

**Issue by Spectra10001** [tmarenko/mff_auto#19]
error message: "Something went wrong while waiting for other players. "
after doing one coop play game with one character with the bot, when it goes to the next character and finds players (the find player screen auto closes and gives the above error in bot log)

**Comment by tmarenko** [comment]
I've tested Coop Missions yesterday and it was working fine. Is that a common error for you?
As far as I can tell, it could be because bot doesn't see `WAITING_FOR_OTHER_PLAYERS` element in 10 seconds after starting the mission:
https://github.com/tmarenko/mff_auto/blob/f21743da7fb02a41972a4b2bfbdfa41bef07eed0/lib/game/missions/coop.py#L69

What's yours emulator resolution and game's graphic settings?
Also, it will be very convenient if you attach a log with this problem.

**Comment by tmarenko** [comment]
No response
