### ISSUE TITLE
Bot Working Optimization.

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#29]
As per my assumption whenever a Battle is complete assuming Epic Quest Battle.
Your Logic = When a Battle is started in Autoplay Mode (bot checks again and again for Battle End) which is using of resource like tesseract.
Optimization = Why not let bot remember in how much time a level is been completed and then only check for Home Screen Button, which could avoid multiple time snaping. Also, after the battle is ended Bot checks for Notification error instead of Home Button first why?

By this maybe #22 Network Error Issue recognization could be ease.

**Comment by tmarenko** [comment]
> Optimization = Why not let bot remember in how much time a level is been completed and then only check for Home Screen Button

Because you could change team or characters in team and this data will becoma irrelevant. Storing this info is addinional problem. Checking only from Home Button is an addionatl problem which I described below.

>  after the battle is ended Bot checks for Notification error

There is multiple notification such as: "All stages done" notification, shield lvl up notification, notification when you see new item in rewards list, etc. Full list here: https://github.com/tmarenko/mff_auto/blob/master/lib/game/notifications.py#L224
All notifications which happen at the of the battle should be checked because bot can't progress without clicking "OK" or "Tap to continue" in-game buttons.

> only check for Home Screen Button

That would work in 6.x.x version of the game but in 7.x.x they introduced transparency for Home button.
Structual similarity (https://github.com/tmarenko/mff_auto/blob/master/lib/structural_similarity/ssim.py) for transparent image isn't so good: for example, that's why I was forced to changed it inside Co-op. Lower similarity for transparent image would cause false recognition. Someone emailed me about this: they set 0.5 threshold for Home button and it falsly triggered "end of battle" condition before even starting the battle.
Checking text from in-game interface seems more stable than images so I usually try to minimaze checking images.

> Network Error Issue recognization could be ease.

Network Error notification can occur anywhere after clicking on button in-game or at the end of the battle.

First problem is to determine when bot will need to check for this notification: 
1) after any `click_button` except while battling (in battle that will slow down spell casting)
2) while looking for "end of battle" condition
3) or maybe check whenever 'wait_until' function is triggered?

The second problem is how to decorate it:
https://github.com/tmarenko/mff_auto/blob/master/lib/game/game.py#L70-L85

There is already two apllyable decorators and there could be problems if we ll need to undecorate function back. Order of decorators isn't set somewhere so it's possible to unpack function at wrong state.
Probably should make separate module for decorators and ordering to prevent this problem.

Honestly, I've just forgot about Network Error feature. I'll look into this feature again.

**Comment by dbzdivik** [comment]
closing this too
